server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vollmed_api
    username: root
    password: 193739
#      jpa:
#        hibernate:
#          ddl-auto: update
#        show-sql: true
#    properties:
#      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
#      hibernate.jdbc.lob.non-contextual-creation: true